import { SEOHead } from '@/components/SEOHead';
import { useLanguage } from '@/contexts/LanguageContext';
import { PageHero } from '@/components/PageHero';

const content = {
  ru: {
    title: 'Политика обработки персональных данных',
    sections: [
      {
        title: '1. Общие положения',
        content: [
          '1.1. Настоящая политика в отношении обработки и обеспечения безопасности персональных данных (далее — Политика) подготовлена в соответствии с Федеральным законом от 27.07.2006 № 152-ФЗ «О персональных данных» (далее – Закон о персональных данных) и иными нормами действующего законодательства Российской Федерации в области защиты персональных данных.',
          '1.2. Политика определяет общий порядок обработки персональных данных Обществом с ограниченной ответственностью «ИННОВЭД» (далее — Компания, Оператор) и общие подходы к обеспечению их конфиденциальности.',
          '1.3. Во исполнение требований ч. 2 ст. 18.1 Закона о персональных данных настоящая Политика публикуется в свободном доступе в информационно-телекоммуникационной сети Интернет на сайте Оператора.',
          '1.4. Политика распространяется на отношения в области обработки персональных данных, возникшие у Оператора как до, так и после утверждения настоящей Политики.',
          '1.5. Обработка персональных данных в Компании основаны на принципах:\n• законности целей и способов обработки персональных данных;\n• соответствия целей обработки персональных данных целям, заранее определенным и заявленным Компанией при сборе персональных данных;\n• достоверности персональных данных, их актуальности и достаточности для целей обработки, недопустимости обработки избыточных по отношению к целям сбора персональных данных;\n• законности и совершенствования организационных и технических мер по обеспечению безопасности персональных данных.'
        ]
      },
      {
        title: '2. Основные понятия, используемые в Политике',
        content: [
          '2.1. Под персональными данными понимается любая информация, относящаяся к прямо или косвенно определённому или определяемому физическому лицу (субъекту персональных данных).',
          '2.2. Оператором персональных данных в рамках настоящей Политики является Компания.',
          `2.3. Обработка персональных данных - любое действие (операция) или совокупность действий (операций) с персональными данными, совершаемых с использованием средств автоматизации или без их использования.`,
          '2.3. Настоящая Политика не устанавливает для Оператора дополнительных обязанностей по сравнению с требованиями действующего законодательства Российской Федерации и носит информационный характер.'
        ]
      },
      {
        title: '3. Объем и категории обрабатываемых персональных данных, категории субъектов персональных данных',
        content: [
          '3.1. Содержание и объем обрабатываемых персональных данных должны соответствовать заявленным Оператором целям обработки, предусмотренным в разд. 4 настоящей Политики. Обрабатываемые персональные данные не должны быть избыточными по отношению к заявленным целям их обработки.',
          '3.2. Оператор может обрабатывать персональные данные следующих категорий субъектов персональных данных:',
          '3.2.1. Кандидаты для приема на работу к Оператору - для целей исполнения трудового законодательства в рамках трудовых и иных непосредственно связанных с ним отношений:\n• фамилия, имя, отчество;\n• пол;\n• гражданство;\n• дата и место рождения;\n• контактные данные;\n• сведения об образовании, опыте работы, квалификации;\n• иные персональные данные, сообщаемые кандидатами самостоятельно в резюме и сопроводительных письмах.',
          '3.2.2. Работники и бывшие работники Оператора - для целей исполнения трудового законодательства в рамках трудовых и иных непосредственно связанных с ним отношений, осуществления пропускного режима:\n• фамилия, имя, отчество;\n• пол;\n• гражданство;\n• дата и место рождения;\n• изображение (фотография);\n• паспортные данные;\n• адрес регистрации по месту жительства;\n• адрес фактического проживания;\n• контактные данные;\n• индивидуальный номер налогоплательщика;\n• страховой номер индивидуального лицевого счета (СНИЛС);\n• сведения об образовании, квалификации, профессиональной подготовке и повышении квалификации;\n• семейное положение, наличие детей, родственные связи;\n• сведения о трудовой деятельности, в том числе наличие поощрений, награждений и (или) дисциплинарных взысканий;\n• данные о регистрации брака;\n• сведения о воинском учете;\n• сведения об инвалидности;\n• сведения об удержании алиментов;\n• сведения о доходе с предыдущего места работы;\n• иные персональные данные, предоставляемые работниками в соответствии с требованиями трудового законодательства.',
          '3.2.3. Члены семьи работников Оператора - для целей исполнения трудового законодательства в рамках трудовых и иных непосредственно связанных с ним отношений:\n• фамилия, имя, отчество;\n• степень родства;\n• год рождения;\n• иные персональные данные, предоставляемые работниками в соответствии с требованиями трудового законодательства.',
          '3.2.4. Контрагенты Оператора (физические лица) - для целей осуществления хозяйственной деятельности в соответствии с уставом ООО «ИННОВЭД»:\n• фамилия, имя, отчество;\n• дата и место рождения;\n• паспортные данные;\n• адрес регистрации по месту жительства;\n• контактные данные;\n• замещаемая должность;\n• индивидуальный номер налогоплательщика;\n• номер расчетного счета;\n• иные персональные данные, предоставляемые клиентами и контрагентами (физическими лицами), необходимые для заключения и исполнения договоров.',
          '3.2.5. Представители (работники) контрагентов Оператора (юридических лиц) - для целей осуществления своей деятельности в соответствии с уставом ООО «ИННОВЭД»:\n• фамилия, имя, отчество;\n• паспортные данные;\n• контактные данные;\n• замещаемая должность;\n• иные персональные данные, предоставляемые представителями (работниками) клиентов и контрагентов, необходимые для заключения и исполнения договоров;',
          '3.2.6. Пользователи сайта Оператора:\n• фамилия, имя, при наличии — отчество;\n• контактные данные (телефон, адрес электронной почты, никнейм в мессенджере, предпочтительном для связи с Пользователем);\n• сведения о грузах, необходимые для оказания услуг по таможенному оформлению;\n• сведения, собираемые посредством метрических программ;\n• иные данные, которые Пользователь сообщает Оператору по собственной инициативе при обращении.',
          '3.3. Также могут автоматически собираться обезличенные данные о посещении Сайта (файлы cookie, техническая информация о браузере и устройстве) для аналитики и улучшения работы Сайта, если такие технологии подключены.',
          '3.4. Оператором не осуществляется обработка специальных категорий персональных данных, касающихся расовой, национальной принадлежности, политических взглядов, религиозных или философских убеждений, состояния здоровья, интимной жизни, за исключением случаев, предусмотренных законодательством РФ.'
        ]
      },
      {
        title: '4. Цели обработки персональных данных',
        content: [
          '4.1. Персональные данные обрабатываются Оператором в объёме, необходимом для достижения следующих целей:\n• осуществление хозяйственной деятельности в соответствии с уставом ООО «ИННОВЭД», в том числе предоставление услуг по таможенному оформлению грузов, заключение и исполнение договоров с контрагентами;\n• исполнение трудового законодательства в рамках трудовых и иных непосредственно связанных с ним отношений, в том числе: содействие работникам в трудоустройстве, получении образования и продвижении по службе, привлечение и отбор кандидатов на работу у Оператора, обеспечение личной безопасности работников, контроль количества и качества выполняемой работы, обеспечение сохранности имущества, ведение кадрового и бухучета, заполнение и передача в уполномоченные органы требуемых форм отчетности, организация постановки на индивидуальный (персонифицированный) учет работников в системах обязательного пенсионного страхования и обязательного социального страхования;\n• взаимодействие с Пользователями (обработка запросов, информирование о статусе услуг, направление необходимой информации);\n• ведение учёта и внутренней отчётности, предусмотренной законодательством;\n• улучшение качества сервисов и работы Сайта, анализ обращений и оптимизация бизнес-процессов;\n• ведение учета клиентов и потенциальных клиентов в системе Битрикс (CRM-система), осуществление взаимодействия с субъектами персональных данных в процессе заключения, исполнения и сопровождения сделок;\n• ведение учёта заключенных договоров/оказанных услуг, анализ бизнес-процессов;\n• сбор с помощью Яндекс Метрики статистической информации о посещаемости сайта, анализ пользовательской активности и оптимизация работы сайта, анализ эффективности рекламы, оценка источников трафика и оптимизация продвижения сайта.',
          '4.2. Обработка персональных данных работников может осуществляться исключительно в целях обеспечения соблюдения действующих законов и иных нормативных правовых актов.'
        ]
      },
      {
        title: '5. Правовые основания обработки',
        content: [
          '5.1. Правовым основанием обработки персональных данных является совокупность нормативных правовых актов, во исполнение которых и в соответствии с которыми Оператор осуществляет обработку персональных данных, в том числе:\n• Конституция Российской Федерации;\n• Гражданский кодекс Российской Федерации;\n• Трудовой кодекс Российской Федерации;\n• Налоговый кодекс Российской Федерации;\n• Федеральный закон от 08.02.1998 N 14-ФЗ "Об обществах с ограниченной ответственностью";\n• Федеральный закон от 06.12.2011 N 402-ФЗ "О бухгалтерском учете";\n• Федеральный закон от 15.12.2001 N 167-ФЗ "Об обязательном пенсионном страховании в Российской Федерации";\n• иные нормативные правовые акты, регулирующие отношения, связанные с деятельностью Оператора.',
          '5.2. Правовым основанием для обработки персональных данных также являются:\n• согласие субъекта персональных данных, выраженное, в том числе, путём отправки формы на Сайте или обращения через указанные средства связи;\n• договоры, заключаемые Оператором с субъектами персональных данных;\n• устав ООО «ИННОВЭД».',
          '5.2. В случаях, прямо предусмотренных законом, обработка персональных данных может осуществляться без отдельного согласия субъекта, строго в пределах, предусмотренных действующим законодательством РФ.'
        ]
      },
      {
        title: '6. Порядок и условия обработки персональных данных',
        content: [
          '6.1. Обработка персональных данных осуществляется с использованием и без использования средств автоматизации, а также путем смешанной обработки в соответствии с принципами и правилами, установленными действующим законодательством РФ.',
          '6.2. К обработке персональных данных допускаются работники Оператора, в должностные обязанности которых входит обработка персональных данных.',
          '6.3. В отдельных случаях Оператор может поручить обработку персональных данных третьим лицам на основании договора, при условии соблюдения такими лицами требований конфиденциальности и безопасности персональных данных.',
          '6.4. Оператор принимает необходимые правовые, организационные и технические меры для защиты персональных данных от неправомерного или случайного доступа к ним, уничтожения, изменения, блокирования, распространения и других несанкционированных действий, в том числе:\n• определяет угрозы безопасности персональных данных при их обработке;\n• принимает локальные нормативные акты и иные документы, регулирующие отношения в сфере обработки и защиты персональных данных;\n• назначает лиц, ответственных за обеспечение безопасности персональных данных в структурных подразделениях и информационных системах Оператора;\n• создает необходимые условия для работы с персональными данными;\n• организует учет документов, содержащих персональные данные;\n• организует работу с информационными системами, в которых обрабатываются персональные данные;\n• хранит персональные данные в условиях, при которых обеспечивается их сохранность и исключается неправомерный доступ к ним;\n• организует обучение работников Оператора, осуществляющих обработку персональных данных.',
          '6.5. Оператор осуществляет хранение персональных данных в форме, позволяющей определить субъекта персональных данных, не дольше, чем этого требует каждая цель обработки персональных данных, если срок хранения персональных данных не установлен федеральным законом, договором.',
          '6.6. Персональные данные на бумажных носителях хранятся в ООО "ИННОВЭД" в течение сроков хранения документов, для которых эти сроки предусмотрены законодательством об архивном деле в РФ (Федеральный закон от 22.10.2004 N 125-ФЗ "Об архивном деле в Российской Федерации", Перечень типовых управленческих архивных документов, образующихся в процессе деятельности государственных органов, органов местного самоуправления и организаций, с указанием сроков их хранения (утв. Приказом Росархива от 20.12.2019 N 236)).',
          '6.7. Срок хранения персональных данных, обрабатываемых в информационных системах персональных данных, соответствует сроку хранения персональных данных на бумажных носителях.',
          '6.8. Оператор прекращает обработку персональных данных в следующих случаях:\n• выявлен факт их неправомерной обработки. Срок прекращения обработки - в течение трех рабочих дней с даты выявления факта неправомерной обработки;\n• достигнута цель их обработки;\n• истек срок действия или отозвано согласие субъекта персональных данных на обработку указанных данных, когда по Закону о персональных данных обработка этих данных допускается только с согласия.',
          '6.9. При достижении целей обработки персональных данных, а также в случае отзыва субъектом персональных данных согласия на их обработку Оператор прекращает обработку этих данных, если:\n• иное не предусмотрено договором, стороной которого, или выгодоприобретателем по которому является субъект персональных данных;\n• Оператор не вправе осуществлять обработку без согласия субъекта персональных данных на основаниях, предусмотренных Законом о персональных данных или иными федеральными законами;\n• иное не предусмотрено другим соглашением между Оператором и субъектом персональных данных.',
          '6.10. При обращении субъекта персональных данных к Оператору с требованием о прекращении обработки персональных данных в срок, не превышающий 10 рабочих дней с даты получения Оператором соответствующего требования, обработка персональных данных прекращается, за исключением случаев, предусмотренных Законом о персональных данных. Указанный срок может быть продлен, но не более чем на пять рабочих дней. Для этого Оператору необходимо направить субъекту персональных данных мотивированное уведомление с указанием причин продления срока.',
          '6.11. При сборе персональных данных, в том числе посредством информационно-телекоммуникационной сети Интернет, запись, систематизация, накопление, хранение, уточнение (обновление, изменение), извлечение персональных данных граждан Российской Федерации с использованием баз данных, находящихся за пределами Российской Федерации, не допускаются, за исключением случаев, указанных в Законе о персональных данных.'
        ]
      },
      {
        title: '7. Актуализация, исправление, удаление, уничтожение персональных данных, ответы на запросы субъектов на доступ к персональным данным',
        content: [
          '7.1. Подтверждение факта обработки персональных данных Оператором, правовые основания и цели обработки персональных данных, а также иные сведения, указанные в ч. 7 ст. 14 Закона о персональных данных, предоставляются Оператором субъекту персональных данных или его представителю в течение 10 рабочих дней с момента обращения либо получения запроса субъекта персональных данных или его представителя. Данный срок может быть продлен, но не более чем на пять рабочих дней. Для этого Оператору следует направить субъекту персональных данных мотивированное уведомление с указанием причин продления срока предоставления запрашиваемой информации.\nВ предоставляемые сведения не включаются персональные данные, относящиеся к другим субъектам персональных данных, за исключением случаев, когда имеются законные основания для раскрытия таких персональных данных.\nЗапрос должен содержать:\n• номер основного документа, удостоверяющего личность субъекта персональных данных или его представителя, сведения о дате выдачи указанного документа и выдавшем его органе;\n• сведения, подтверждающие участие субъекта персональных данных в отношениях с Оператором (номер договора, дата заключения договора, условное словесное обозначение и (или) иные сведения), либо сведения, иным образом подтверждающие факт обработки персональных данных Оператором;\n• подпись субъекта персональных данных или его представителя.\nЗапрос может быть направлен в форме электронного документа и подписан электронной подписью в соответствии с законодательством Российской Федерации.\nОператор предоставляет сведения, указанные в ч. 7 ст. 14 Закона о персональных данных, субъекту персональных данных или его представителю в той форме, в которой направлены соответствующие обращение либо запрос, если иное не указано в обращении или запросе.\nЕсли в обращении (запросе) субъекта персональных данных не отражены в соответствии с требованиями Закона о персональных данных все необходимые сведения или субъект не обладает правами доступа к запрашиваемой информации, то ему направляется мотивированный отказ.\nПраво субъекта персональных данных на доступ к его персональным данным может быть ограничено в соответствии с ч. 8 ст. 14 Закона о персональных данных, в том числе если доступ субъекта персональных данных к его персональным данным нарушает права и законные интересы третьих лиц.',
          '7.2. В случае выявления неточных персональных данных при обращении субъекта персональных данных или его представителя либо по их запросу или по запросу Роскомнадзора Оператор осуществляет блокирование персональных данных, относящихся к этому субъекту персональных данных, с момента такого обращения или получения указанного запроса на период проверки, если блокирование персональных данных не нарушает права и законные интересы субъекта персональных данных или третьих лиц. В случае подтверждения факта неточности персональных данных Оператор на основании сведений, представленных субъектом персональных данных или его представителем либо Роскомнадзором, или иных необходимых документов уточняет персональные данные в течение семи рабочих дней со дня представления таких сведений и снимает блокирование персональных данных.',
          '7.3. В случае выявления неправомерной обработки персональных данных при обращении (запросе) субъекта персональных данных или его представителя либо Роскомнадзора Оператор осуществляет блокирование неправомерно обрабатываемых персональных данных, относящихся к этому субъекту персональных данных, с момента такого обращения или получения запроса.',
          '7.4. При выявлении Оператором, Роскомнадзором или иным заинтересованным лицом факта неправомерной или случайной передачи (предоставления, распространения) персональных данных (доступа к персональным данным), повлекшей нарушение прав субъектов персональных данных, Оператор:\n• в течение 24 часов - уведомляет Роскомнадзор о произошедшем инциденте, предполагаемых причинах, повлекших нарушение прав субъектов персональных данных, предполагаемом вреде, нанесенном правам субъектов персональных данных, и принятых мерах по устранению последствий инцидента, а также предоставляет сведения о лице, уполномоченном Оператором на взаимодействие с Роскомнадзором по вопросам, связанным с инцидентом;\n• в течение 72 часов - уведомляет Роскомнадзор о результатах внутреннего расследования выявленного инцидента и предоставляет сведения о лицах, действия которых стали его причиной (при наличии).',
          '7.5. Порядок уничтожения персональных данных Оператором.',
          '7.5.1. Условия и сроки уничтожения персональных данных Оператором:\n• достижение цели обработки персональных данных либо утрата необходимости достигать эту цель - в течение 30 дней;\n• достижение максимальных сроков хранения документов, содержащих персональные данные, - в течение 30 дней;\n• предоставление субъектом персональных данных (его представителем) подтверждения того, что персональные данные получены незаконно или не являются необходимыми для заявленной цели обработки, - в течение семи рабочих дней;\n• отзыв субъектом персональных данных согласия на обработку его персональных данных, если их сохранение для цели их обработки более не требуется, - в течение 30 дней.',
          '7.5.2. При достижении цели обработки персональных данных, а также в случае отзыва субъектом персональных данных согласия на их обработку персональные данные подлежат уничтожению, если:\n• иное не предусмотрено договором, стороной которого, выгодоприобретателем или поручителем по которому является субъект персональных данных;\n• оператор не вправе осуществлять обработку без согласия субъекта персональных данных на основаниях, предусмотренных Законом о персональных данных или иными федеральными законами;\n• иное не предусмотрено другим соглашением между Оператором и субъектом персональных данных.',
          '7.5.3. Уничтожение персональных данных осуществляется лицом, назначенным приказом генерального директора ООО "ИННОВЭД".',
          '7.5.4. Способы уничтожения персональных данных устанавливаются в локальных нормативных актах Оператора.'
        ]
      }
    ]
  },
  en: {
    title: 'Personal Data Processing Policy',
    sections: [
      {
        title: '1. General Provisions',
        content: [
          '1.1. This policy regarding the processing and security of personal data (hereinafter — the Policy) has been prepared in accordance with Federal Law No. 152-FZ of 27.07.2006 "On Personal Data" (hereinafter — the Personal Data Law) and other applicable legislation of the Russian Federation in the field of personal data protection.',
          '1.2. The Policy defines the general procedure for processing personal data by Limited Liability Company "INNOVED" (hereinafter — the Company, the Operator) and the general approaches to ensuring their confidentiality.',
          '1.3. In fulfillment of the requirements of Part 2, Article 18.1 of the Personal Data Law, this Policy is published for free access on the Internet on the Operator\'s website.',
          '1.4. The Policy applies to relations in the field of personal data processing that have arisen for the Operator both before and after the approval of this Policy.',
          '1.5. The processing of personal data at the Company is based on the following principles:\n• lawfulness of the purposes and methods of processing personal data;\n• conformity of the purposes of processing personal data with the purposes predetermined and declared by the Company when collecting personal data;\n• accuracy of personal data, their relevance and sufficiency for the purposes of processing, and inadmissibility of processing personal data that are excessive in relation to the purposes of their collection;\n• lawfulness and improvement of organizational and technical measures to ensure the security of personal data.'
        ]
      },
      {
        title: '2. Basic Concepts Used in the Policy',
        content: [
          '2.1. Personal data means any information relating to a directly or indirectly identified or identifiable natural person (personal data subject).',
          '2.2. The personal data operator under this Policy is the Company.',
          `2.3. Processing of personal data means any action (operation) or set of actions (operations) performed with personal data, whether using automation tools or without their use.`,
          '2.3. This Policy does not impose additional obligations on the Operator beyond the requirements of the current legislation of the Russian Federation and is informational in nature.'
        ]
      },
      {
        title: '3. Scope and Categories of Processed Personal Data, Categories of Personal Data Subjects',
        content: [
          '3.1. The content and scope of processed personal data must correspond to the purposes of processing declared by the Operator, provided for in Section 4 of this Policy. Processed personal data must not be excessive in relation to the declared purposes of their processing.',
          '3.2. The Operator may process personal data of the following categories of personal data subjects:',
          '3.2.1. Candidates for employment with the Operator — for the purposes of fulfilling labor legislation within the framework of labor and other relations directly related thereto:\n• last name, first name, patronymic;\n• gender;\n• citizenship;\n• date and place of birth;\n• contact details;\n• information on education, work experience, qualifications;\n• other personal data provided by candidates independently in resumes and cover letters.',
          '3.2.2. Employees and former employees of the Operator — for the purposes of fulfilling labor legislation within the framework of labor and other relations directly related thereto, and for implementing access control:\n• last name, first name, patronymic;\n• gender;\n• citizenship;\n• date and place of birth;\n• image (photograph);\n• passport data;\n• registration address at place of residence;\n• actual residential address;\n• contact details;\n• individual taxpayer number;\n• insurance number of an individual personal account (SNILS);\n• information on education, qualifications, professional training and advanced training;\n• marital status, presence of children, family relationships;\n• information on employment activity, including incentives, awards and/or disciplinary sanctions;\n• marriage registration data;\n• military registration information;\n• disability information;\n• information on alimony withholding;\n• information on income from previous place of employment;\n• other personal data provided by employees in accordance with the requirements of labor legislation.',
          '3.2.3. Family members of the Operator\'s employees — for the purposes of fulfilling labor legislation within the framework of labor and other relations directly related thereto:\n• last name, first name, patronymic;\n• degree of kinship;\n• year of birth;\n• other personal data provided by employees in accordance with the requirements of labor legislation.',
          '3.2.4. The Operator\'s counterparties (natural persons) — for the purposes of carrying out business activities in accordance with the charter of LLC "INNOVED":\n• last name, first name, patronymic;\n• date and place of birth;\n• passport data;\n• registration address at place of residence;\n• contact details;\n• position held;\n• individual taxpayer number;\n• bank account number;\n• other personal data provided by clients and counterparties (natural persons) necessary for concluding and performing contracts.',
          '3.2.5. Representatives (employees) of the Operator\'s counterparties (legal entities) — for the purposes of carrying out their activities in accordance with the charter of LLC "INNOVED":\n• last name, first name, patronymic;\n• passport data;\n• contact details;\n• position held;\n• other personal data provided by representatives (employees) of clients and counterparties necessary for concluding and performing contracts;',
          '3.2.6. Users of the Operator\'s website:\n• surname, first name, and patronymic (if available);\n• contact details (phone, email address, messenger username preferred for communication with the User);\n• cargo information necessary for the provision of customs clearance services;\n• information collected through analytics/metrics programs;\n• other data that the User provides to the Operator on their own initiative when contacting.',
          '3.3. Anonymized data about visits to the Website (cookie files, technical information about the browser and device) may also be automatically collected for analytics and improvement of the Website\'s operation, if such technologies are enabled.',
          '3.4. The Operator does not process special categories of personal data relating to racial or ethnic origin, political views, religious or philosophical beliefs, state of health, or intimate life, except in cases provided for by the legislation of the Russian Federation.'
        ]
      },
      {
        title: '4. Purposes of Personal Data Processing',
        content: [
          '4.1. Personal data is processed by the Operator to the extent necessary to achieve the following purposes:\n• carrying out business activities in accordance with the charter of LLC "INNOVED", including the provision of customs clearance services for cargo, and the conclusion and performance of contracts with counterparties;\n• fulfillment of labor legislation within the framework of labor and other relations directly related thereto, including: assisting employees with employment, education and career advancement, attracting and selecting candidates for employment with the Operator, ensuring the personal safety of employees, monitoring the quantity and quality of work performed, ensuring the safekeeping of property, maintaining personnel and accounting records, completing and submitting required reporting forms to authorized bodies, organizing individual (personalized) registration of employees in the mandatory pension insurance and mandatory social insurance systems;\n• interaction with Users (processing requests, informing about the status of services, sending necessary information);\n• maintaining records and internal reporting required by law;\n• improving the quality of services and the operation of the Website, analyzing inquiries and optimizing business processes;\n• maintaining records of clients and potential clients in the Bitrix system (CRM system), and interacting with personal data subjects during the conclusion, performance and support of transactions;\n• maintaining records of concluded contracts/services rendered, and analyzing business processes;\n• collecting statistical information on website traffic via Yandex Metrica, analyzing user activity, optimizing the Website\'s operation, analyzing advertising effectiveness, evaluating traffic sources, and optimizing website promotion.',
          '4.2. The processing of employees\' personal data may be carried out exclusively for the purposes of ensuring compliance with applicable laws and other regulatory legal acts.'
        ]
      },
      {
        title: '5. Legal Grounds for Processing',
        content: [
          '5.1. The legal grounds for processing personal data are a body of regulatory legal acts, in pursuance of and in accordance with which the Operator processes personal data, including:\n• the Constitution of the Russian Federation;\n• the Civil Code of the Russian Federation;\n• the Labor Code of the Russian Federation;\n• the Tax Code of the Russian Federation;\n• Federal Law No. 14-FZ of 08.02.1998 "On Limited Liability Companies";\n• Federal Law No. 402-FZ of 06.12.2011 "On Accounting";\n• Federal Law No. 167-FZ of 15.12.2001 "On Mandatory Pension Insurance in the Russian Federation";\n• other regulatory legal acts governing relations connected with the Operator\'s activities.',
          '5.2. The legal grounds for processing personal data also include:\n• the consent of the personal data subject, expressed, among other things, by submitting a form on the Website or contacting through the specified means of communication;\n• contracts concluded by the Operator with personal data subjects;\n• the charter of LLC "INNOVED".',
          '5.2. In cases directly provided for by law, personal data may be processed without the separate consent of the subject, strictly within the limits provided for by the current legislation of the Russian Federation.'
        ]
      },
      {
        title: '6. Procedure and Conditions for Processing Personal Data',
        content: [
          '6.1. Personal data processing is carried out with and without the use of automation tools, as well as through mixed processing, in accordance with the principles and rules established by the current legislation of the Russian Federation.',
          '6.2. Access to the processing of personal data is granted to Operator employees whose job duties include the processing of personal data.',
          '6.3. In certain cases, the Operator may entrust the processing of personal data to third parties on the basis of a contract, provided that such persons comply with the requirements of confidentiality and security of personal data.',
          '6.4. The Operator takes the necessary legal, organizational and technical measures to protect personal data from unlawful or accidental access, destruction, modification, blocking, distribution and other unauthorized actions, including:\n• identifying threats to the security of personal data during their processing;\n• adopting local regulatory acts and other documents governing relations in the field of personal data processing and protection;\n• appointing persons responsible for ensuring the security of personal data in the Operator\'s structural divisions and information systems;\n• creating the necessary conditions for working with personal data;\n• organizing accounting of documents containing personal data;\n• organizing work with information systems in which personal data are processed;\n• storing personal data under conditions that ensure their safekeeping and preclude unlawful access to them;\n• organizing training for Operator employees who process personal data.',
          '6.5. The Operator stores personal data in a form that allows the identification of the personal data subject for no longer than required by each purpose of personal data processing, unless the storage period for personal data is established by federal law or a contract.',
          '6.6. Personal data on paper media are stored by LLC "INNOVED" for the storage periods established for documents by the legislation on archival matters in the Russian Federation (Federal Law No. 125-FZ of 22.10.2004 "On Archival Matters in the Russian Federation", the List of Standard Administrative Archival Documents Generated in the Course of the Activities of State Bodies, Local Self-Government Bodies and Organizations, Indicating Their Storage Periods (approved by Order of Rosarkhiv No. 236 of 20.12.2019)).',
          '6.7. The storage period for personal data processed in personal data information systems corresponds to the storage period for personal data on paper media.',
          '6.8. The Operator terminates the processing of personal data in the following cases:\n• a fact of their unlawful processing has been identified. The processing shall be terminated within three business days from the date the fact of unlawful processing is identified;\n• the purpose of their processing has been achieved;\n• the term has expired or the personal data subject\'s consent to the processing of the specified data has been withdrawn, when, under the Personal Data Law, the processing of this data is permitted only with consent.',
          '6.9. Upon achieving the purposes of personal data processing, as well as in the event that the personal data subject withdraws consent to their processing, the Operator terminates the processing of this data, unless:\n• otherwise provided by a contract to which the personal data subject is a party or beneficiary;\n• the Operator is entitled to carry out processing without the consent of the personal data subject on grounds provided for by the Personal Data Law or other federal laws;\n• otherwise provided by another agreement between the Operator and the personal data subject.',
          '6.10. When a personal data subject applies to the Operator with a request to terminate the processing of personal data, the processing of personal data shall be terminated within a period not exceeding 10 business days from the date the Operator receives the corresponding request, except in cases provided for by the Personal Data Law. This period may be extended, but by no more than five business days. To do so, the Operator must send the personal data subject a reasoned notice indicating the reasons for the extension.',
          '6.11. When collecting personal data, including via the Internet, the recording, systematization, accumulation, storage, clarification (updating, modification) and retrieval of personal data of citizens of the Russian Federation using databases located outside the Russian Federation are not permitted, except in cases specified in the Personal Data Law.'
        ]
      },
      {
        title: '7. Updating, Correction, Deletion, Destruction of Personal Data, and Responses to Subject Access Requests',
        content: [
          '7.1. Confirmation of the fact of personal data processing by the Operator, the legal grounds and purposes of personal data processing, as well as other information specified in Part 7, Article 14 of the Personal Data Law, are provided by the Operator to the personal data subject or their representative within 10 business days from the moment of contact or receipt of a request from the personal data subject or their representative. This period may be extended, but by no more than five business days. To do so, the Operator must send the personal data subject a reasoned notice indicating the reasons for extending the period for providing the requested information.\nThe information provided does not include personal data relating to other personal data subjects, except in cases where there are legal grounds for disclosing such personal data.\nThe request must contain:\n• the number of the main identity document of the personal data subject or their representative, information on the date of issue of the specified document and the authority that issued it;\n• information confirming the personal data subject\'s participation in relations with the Operator (contract number, date of conclusion of the contract, a conventional verbal designation and/or other information), or information otherwise confirming the fact of personal data processing by the Operator;\n• the signature of the personal data subject or their representative.\nThe request may be sent in the form of an electronic document and signed with an electronic signature in accordance with the legislation of the Russian Federation.\nThe Operator provides the information specified in Part 7, Article 14 of the Personal Data Law to the personal data subject or their representative in the form in which the corresponding inquiry or request was sent, unless otherwise indicated in the inquiry or request.\nIf the inquiry (request) of the personal data subject does not, in accordance with the requirements of the Personal Data Law, reflect all necessary information, or the subject does not have access rights, the provision of information may be refused in the manner established by Part 8, Article 14 of the Personal Data Law.\nThe right of the personal data subject to access their personal data may be restricted in accordance with federal laws, including where the personal data subject\'s access to their personal data violates the rights and legitimate interests of third parties.',
          '7.2. If inaccurate personal data is identified upon the request of the personal data subject or their representative, or at their request, or at the request of Roskomnadzor, the Operator blocks the personal data relating to that personal data subject from the moment of such request or receipt of the said request for the period of verification, unless blocking the personal data violates the rights and legitimate interests of the personal data subject or third parties. If the fact of inaccuracy of the personal data is confirmed, the Operator, on the basis of information provided by the personal data subject or their representative or by Roskomnadzor, or other necessary documents, updates the personal data within seven business days from the date such information is provided and lifts the blocking of the personal data.',
          '7.3. If unlawful processing of personal data is identified upon the request (inquiry) of the personal data subject or their representative, or of Roskomnadzor, the Operator blocks the unlawfully processed personal data relating to that personal data subject from the moment of such request or receipt of the request.',
          '7.4. If the Operator, Roskomnadzor or any other interested party identifies a fact of unlawful or accidental transfer (provision, dissemination) of personal data (access to personal data) that has resulted in a violation of the rights of personal data subjects, the Operator:\n• within 24 hours — notifies Roskomnadzor of the incident that occurred, the presumed causes that led to the violation of the rights of personal data subjects, the presumed harm caused to the rights of personal data subjects, and the measures taken to eliminate the consequences of the incident, and also provides information about the person authorized by the Operator to interact with Roskomnadzor on matters related to the incident;\n• within 72 hours — notifies Roskomnadzor of the results of the internal investigation of the identified incident and provides information about the persons whose actions caused it (if any).',
          '7.5. Procedure for the destruction of personal data by the Operator.',
          '7.5.1. Conditions and terms for the destruction of personal data by the Operator:\n• achievement of the purpose of personal data processing or loss of the need to achieve that purpose — within 30 days;\n• reaching the maximum storage periods for documents containing personal data — within 30 days;\n• provision by the personal data subject (their representative) of confirmation that the personal data was obtained unlawfully or is not necessary for the declared purpose of processing — within seven business days;\n• withdrawal by the personal data subject of consent to the processing of their personal data, if their retention for the purpose of processing is no longer required — within 30 days.',
          '7.5.2. Upon achieving the purpose of personal data processing, as well as in the event that the personal data subject withdraws consent to their processing, the personal data shall be destroyed, unless:\n• otherwise provided by a contract to which the personal data subject is a party, beneficiary or guarantor;\n• the operator is entitled to carry out processing without the consent of the personal data subject on grounds provided for by the Personal Data Law or other federal laws;\n• otherwise provided by another agreement between the Operator and the personal data subject.',
          '7.5.3. The destruction of personal data is carried out by a person appointed by order of the General Director of LLC "INNOVED".',
          '7.5.4. The methods of destroying personal data are established in the Operator\'s local regulatory acts.'
        ]
      }
    ]
  }
};

const Privacy = () => {
  const { language } = useLanguage();
  const text = content[language];

  return (
    <>
      <SEOHead language={language} page="privacy" />
      <PageHero title={text.title} />
      
      <div className="py-12 bg-background">
        <div className="container mx-auto px-4 max-w-4xl">
          <div className="space-y-8">
            {text.sections.map((section, index) => (
              <section key={index} className="bg-card p-6 rounded-lg shadow-card border border-border">
                <h2 className="text-xl font-semibold text-card-foreground mb-4">
                  {section.title}
                </h2>
                <div className="space-y-3">
                  {section.content.map((paragraph, pIndex) => (
                    <p key={pIndex} className="text-muted-foreground leading-relaxed whitespace-pre-line">
                      {paragraph}
                    </p>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </div>
      </div>
    </>
  );
};

export default Privacy;
