// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbephkgmwanbgemvdvks.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZXBoa2dtd2FuYmdlbXZkdmtzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NTI4MDYsImV4cCI6MjA5MDQyODgwNn0.V3fBH9nnAdbIOU8ZA49wxXQTz3y2lVwgEVyBx0W5FZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});